# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Lane for distribution"
      lane :distribute do
          gradle(task: 'clean')
          gradle(
            task: "assemble",
            build_type: "debug",
  	)
          firebase_app_distribution(
              app: ENV['APP_ID'],
  	    groups: ENV['FIREBASE_GROUPS'],
  	    release_notes_file: ENV['RELEASE_NOTES_FILE'],
         	    debug: true,
  	)
  end

    lane :publishReleaseToStore do
      # 경로들
      keystore = File.join(Dir.pwd, "keystore/housweet.jks")
      json_file = File.join(Dir.pwd, "fastlane/roomshare-6d8cd-95b994871b09.json")

      # (선택) 로컬에서 서명 주입이 필요할 때만 사용
      # 보통은 app/build.gradle의 signingConfigs를 쓰면 이 블록은 불필요
      # 필요하다면 ENV로 빼두세요.
      gradle(
        task: "bundleRelease",
        print_command: true,
        properties: {
          "android.injected.signing.store.file" => keystore,
          "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
          "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
          "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
        }
      )

      # AAB 자동 감지되지만, 확실히 하려면 aab: 로 경로 지정 가능
      # aab_path = "app/build/outputs/bundle/release/app-release.aab"

      upload_to_play_store(
        track: "internal",            # 테스트면 internal이 편함(또는 'production'도 가능)
        release_status: "draft",      # 초안으로 올리기
        json_key: json_file,          # 파일 "경로"를 줄 때는 json_key
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
        # aab: aab_path              # 명시하고 싶으면 주석 해제
      )
    end

end
